### ISSUE TITLE
Upload / Download / Ping metrics not accurate?

### ISSUE THREAD

**Issue by n1nj4888** [QuadStingray/docker-speedtest-influxdb#5]
Hi There,

I’m only getting max 50Mbps / 3Mbps Download / Upload from this Docker image but my line is 1Gbps. 

If I use a different speedtest method (for example https://hub.docker.com/r/atribe/speedtest-for-influxdb-and-grafana/ or speedtest-cli) running on the same host I get around 700-800Mbps Down and 400-500 Mbps up. 

Also the ping stats seem to be inaccurate showing around 2-5seconds whereas the other methods above show around 10ms. 

I’ve tried your grafana dashboard and viewed the stats from the Docker container logs - Any idea why the metrics are much worse than expected (and why they disagree so much with the other methods)?

Thanks!

**Comment by n1nj4888** [comment]
This sounds like it’s the same issue fixed here? https://github.com/frdmn/docker-speedtest-grafana/issues/3

**Comment by QuadStingray** [comment]
It could be that there is a similar error, but the error in my environment (200 Mbit) does not occur or only occurs slightly.

Since I am currently dissatisfied with the results of speedtest.net (also with other tools), I started to refactor the image on the speed test from https://github.com/m-lab (https://www.measurementlab.net), based on the NDT7 Protocol.

This is currently still work in progress, but I would like to build the current status as a snapshot so that you can test the result?

**Comment by n1nj4888** [comment]
Hi @QuadStingray, is the new version v1.0.0 (“ndt7” tag) the “snapshot” version you mention above? If so assume it is ready for testing?

**Comment by QuadStingray** [comment]
Hi, 
I refactored again from my scala branch to an ndt7 branch with go. Version 1.0.0 is build at that moment
